stages:
  load_aoi:
    cmd: python -m data_preparation.pipeline.01_aoi
    deps:
      - data_preparation/pipeline/01_aoi.py
      - configs/config.yaml
      - configs/data_preparation/aoi.yaml
      - data/natural-earth/ne_10m_admin_0_countries.geojson
    params:
      - configs/data_preparation/aoi.yaml:
    outs:
      - data/aoi.geojson:
          cache: true
          persist: true

  generate_grid:
    cmd: python -m data_preparation.pipeline.02_grid
    deps:
      - data_preparation/pipeline/02_grid.py
      - data_preparation/load_data/processors.py
      - data/aoi.geojson
      - configs/config.yaml
      - configs/data_preparation/preprocessing.yaml
    params:
      - configs/data_preparation/preprocessing.yaml:
    outs:
      - data/grid.gpkg

  select_tiles:
    cmd: python -m data_preparation.pipeline.03_select_tiles
    deps:
      - data_preparation/pipeline/03_select_tiles.py
      - data_preparation/load_data/processors.py
      - data/grid.gpkg
      - configs/config.yaml
      - configs/data_preparation/sampling.yaml
    params:
      - configs/data_preparation/sampling.yaml:
    outs:
      - data/grid_selected.gpkg:
          cache: true
          persist: true

  download_imagery:
    cmd: python -m data_preparation.pipeline.04_download
    deps:
      - data_preparation/pipeline/04_download.py
      - data_preparation/load_data/loader.py
      - data/grid_selected.gpkg
      - configs/config.yaml
      - configs/data_preparation/download.yaml
      - configs/data_preparation/preprocessing.yaml
    params:
      - configs/data_preparation/download.yaml:
      - configs/data_preparation/preprocessing.yaml:
    outs:
      - data/imagery:
          persist: true

  generate_labels:
    cmd: python -m data_preparation.pipeline.05_label
    deps:
      - data_preparation/pipeline/05_label.py
      - data/imagery
      - data/worldcover/v200/2021/esa_worldcover_grid.geojson
      - configs/config.yaml
      - configs/data_preparation/labels.yaml
      - configs/data_preparation/download.yaml
    params:
      - configs/data_preparation/labels.yaml:
      - configs/data_preparation/download.yaml:
    outs:
      - data/labels:
          persist: true

  patchify:
    cmd: python -m data_preparation.pipeline.06_patchify
    deps:
      - data_preparation/pipeline/06_patchify.py
      - data_preparation/patchify/io.py
      - utils/logging.py
      - data/imagery
      - data/labels
      - configs/config.yaml
      - configs/data_preparation/patchify.yaml
    params:
      - configs/data_preparation/patchify.yaml:
    outs:
      - data/patches:
          persist: true

  build_index:
    cmd: python -m data_preparation.pipeline.07_build_index ++index.num_workers=8
    deps:
      - data_preparation/pipeline/07_build_index.py
      - data_preparation/patchify/io.py
      - data_preparation/patchify/stats.py
      - data_preparation/index/utils.py
      - utils/logging.py
      - data/imagery
      - data/labels
      - data/patches
      - data/aoi.geojson
      - configs/config.yaml
      - configs/data_preparation/index.yaml
    params:
      - configs/data_preparation/index.yaml:
    outs:
      - data/index/dataset_index.csv


  assign_splits:
    cmd: python -m data_preparation.pipeline.08_assign_splits
    deps:
      - data_preparation/pipeline/08_assign_splits.py
      - data_preparation/index/hash_split.py
      - data/index/dataset_index.csv
      - data/aoi.geojson
      - configs/config.yaml
      - configs/data_preparation/split.yaml
    params:
      - configs/data_preparation/split.yaml:
    outs:
      - data/index/dataset_index_with_split.csv
      - data/index/train_index.csv
      - data/index/val_index.csv
      - data/index/test_index.csv
      - data/index/ood_index.csv

  compute_norm_stats:
    cmd: python -m data_preparation.pipeline.09_compute_norm_stats
    deps:
      - data/index/dataset_index_with_split.csv
      - data_preparation/pipeline/09_compute_norm_stats.py
      - configs/config.yaml
      - configs/data_preparation/norm_stats.yaml
    params:
      - configs/data_preparation/norm_stats.yaml:
    outs:
      - data/stats/norm_stats.json:
          cache: true
