stages:
  load_aoi:
    cmd: python -m scripts.load_data.pipeline.01_aoi
    deps:
      - scripts/load_data/pipeline/01_aoi.py
      - conf/load_data/params.yaml
      - data/natural-earth/ne_10m_admin_0_countries.geojson
    params:
      - conf/load_data/params.yaml:
        - aoi
    outs:
      - data/aoi.geojson:
          cache: true
          persist: true

  generate_grid:
    cmd: python -m scripts.load_data.pipeline.02_grid
    deps:
      - scripts/load_data/pipeline/02_grid.py
      - data/aoi.geojson
      - conf/load_data/params.yaml
    params:
      - conf/load_data/params.yaml:
        - preprocessing
    outs:
      - data/grid.geojson

  download_imagery:
    cmd: python -m scripts.load_data.pipeline.03_download
    deps:
      - scripts/load_data/pipeline/03_download.py
      - scripts/load_data/loader.py
      - data/grid.geojson
      - conf/load_data/params.yaml
    params:
      - conf/load_data/params.yaml:
        - download
        - preprocessing
    outs:
      - data/imagery:
          persist: true

  generate_labels:
    cmd: python -m scripts.load_data.pipeline.04_label
    deps:
      - scripts/load_data/pipeline/04_label.py
      - data/imagery
      - data/worldcover/v200/2021/esa_worldcover_grid.geojson
      - conf/load_data/params.yaml
    params:
      - conf/load_data/params.yaml:
        - labels
        - download
    outs:
      - data/labels:
          persist: true
