[workspace]
authors = ["Anton Ustinov <ustinov.ant@gmail.com>"]
channels = ["conda-forge"]
name = "gfm-landcover-mapping"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
pip = "*"
rasterio = "*"
gdal = "*"
proj = "*"
geos = "*"
fiona = "*"
shapely = "*"
pyproj = "*"
ipykernel = "*"
jupyterlab = "*"
numpy = ">=2.4.0,<3"

[system-requirements]
cuda = "12"

[target.linux-64.dependencies]
pytorch-gpu = ">=2.9.1,<3"
cuda-version = "12.9.*"
torchvision = ">=0.24.1,<0.25"

[target.osx-arm64.dependencies]
pytorch = ">=2.9.1,<3"
torchvision = ">=0.24.1,<0.25"

[pypi-dependencies]
sentinelhub = ">=3.11.3, <4"
requests = "*"
pandas = ">=2.3.3, <3"
matplotlib = ">=3.10.8, <4"
click = "*"
geopandas = ">=1.1.2, <2"
requests-oauthlib = ">=2.0.0, <3"
boto3 = "*"
hydra-core = ">=1.3.2, <2"
pytorch-lightning = ">=2.6.0, <3"
torchmetrics = ">=1.8.2, <2"
onnx = "*"
onnxscript = ">=0.1.0"

[feature.dev.pypi-dependencies]
pre-commit = "*"
ruff = "*"
mypy = "*"
types-requests = "*"
pytest = "*"
dvc = { version = ">=3.65.0, <4", extras = ["s3"] }
jupyterlab = "*"
seaborn = ">=0.13.2, <0.14"

[feature.dev.tasks]
lint-all = "pre-commit run --all-files"
test = "pytest"
lab = "jupyter lab"

[environments]
dev = ["dev"]
